### PR TITLE
Make `newline` index search cross-platform

### LINKED ISSUE #19: Different behavior for different end of line characters
The library throws "Wrong error" error for CRLF end of line (EOL) characters, but works fine for LF ones in the same test cases.

Steps to reproduce:
1. Create `test/index.errors.ts` and write cases, that should throw an error. For example:
    ```typescript
    // THROWS Type 'string' is not assignable to type 'number'.
    const variable: number = "variable";
    ```
2. Make sure that file has CRLF EOL.
3. Run `check-dts`.
    Actual behavior:
    ```
    ✖ src\tests\index.errors.ts:2:7: Wrong error
      Expected: Type 'string' is not assignable to type 'number'.
      Got: Type 'string' is not assignable to type 'number'.
    ```

    Expected behavior:
    ```
    ✔ src\tests\index.errors.ts
    ```
4. Change CRLF EOL to LF one.
5. Run `check-dts`.
    Actual behavior:
    ```
    ✔ src\tests\index.errors.ts
    ```

### PR DESCRIPTION
**Pull request by vasilii-kovalev**
Closes #19

What has been done:
* Changed `newline` index search using a regexp, which takes into account both `\n` and `\r\n` characters. Since a regexp is used instead of a string, `indexOf` has been changed to `search`.
  Inspired by: https://stackoverflow.com/questions/8125709/javascript-how-to-split-newline/45709854#45709854
* Checked the work locally using [yarn link](https://classic.yarnpkg.com/en/docs/cli/link/) feature.

### CODE REVIEW

**Comment by vasilii-kovalev** [comment]
As I can see, there are some problems with snapshots. I saw, that folder delimiters of folders/files are different for different platform (in snapshots it is like `test/b.errors`, on Windows it is like `test\b.errors`). Thus, I can't update the snapshots since it will break the future development/support.

**Comment by ai** [comment]
> As I can see, there are some problems with snapshots.

On CI or on your Windows machine?

**Comment by vasilii-kovalev** [comment]
Both on CI and Windows (locally).

**Comment by vasilii-kovalev** [comment]
I mean, I can see the failing snapshots on CI, but I can't fix them, because it will introduce some Windows-specific stuff.

**Comment by ai** [comment]
> I mean, I can see the failing snapshots on CI, but I can't fix them, because it will introduce some Windows-specific stuff.

Why? CI tests was fine before these changes.

It looks like you fix logic for Windows, but broke for Linux (CI uses Linux).

**Comment by vasilii-kovalev** [comment]
OK, I'll try to double-check it.

**Comment by vasilii-kovalev** [comment]
I just missed, that `search` doesn't accept `position` parameter.

File: check.js [hunk 1]
```diff
@@ -47,7 +47,21 @@ async function parseTest(files) {
       while (true) {
         pos = source.indexOf(PREFIX, prev + 1)
         if (pos === -1) break
-        let newline = source.indexOf('\n', pos)
+        let newline = source.slice(pos).search(/\r?\n/)
```
Comment (ai) [inline check.js:50]: This way is slow (we need to recreate the string in memory).

There is a better with `RegExp.lastIndex` https://github.com/postcss/postcss/blob/main/lib/tokenize.js#L173-L174

Comment (vasilii-kovalev) [reply check.js:50]: That's how it could look like:
```javascript
const regexp = /\r?\n/g;
regexp.lastIndex = pos + 1;
regexp.test(source);
let newline = regexp.lastIndex - 2
```

I also tried to use [this `if-else`](https://github.com/postcss/postcss/blob/main/lib/tokenize.js#L175-L179), but it changes nothing.

If I understand correctly, ` - 2` is used to:
1. Compensate `+1` in `pos + 1`
2. Compensate a newline character's index (`\n`)

The problem is in the 2nd case: it will work correctly either for `\n` or `\r\n`. It seems we need 2 regular expressions: one is for ~~monsters~~ `\r\n`, the other is for ~~humans~~ `\n`. If the first one doesn't help, use the other, like this:
```javascript
const WINDOWS_NEW_LINE = /\r\n/g;
WINDOWS_NEW_LINE.lastIndex = pos + 1;
WINDOWS_NEW_LINE.test(source);

let newline;

if (WINDOWS_NEW_LINE.lastIndex !== 0) {
  newline = WINDOWS_NEW_LINE.lastIndex - 2
} else {
  const UNIX_NEW_LINE = /\n/g;
  UNIX_NEW_LINE.lastIndex = pos + 1;
  UNIX_NEW_LINE.test(source);
  newline = UNIX_NEW_LINE.lastIndex - 1
}
```

Does the speed worth it?

Comment (ai) [reply check.js:50]: Nope, it looks too complicated
